ekf_node:
  ros__parameters:
    use_sim_time: True

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf: true
    two_d_mode: true
    #add
    # transform_time_offset: 0.1
    # transform_timeout: 0.1

    frequency: 100.0

    # odom0: jackal_velocity_controller/odom
    odom0: odom
    odom0_config: [true, true, false,
                  false, false, false,
                  true, true, false,
                  false, false, true,
                  false, false, false]
        #        [x_pos   , y_pos    , z_pos,
        #         roll    , pitch    , yaw,
        #         x_vel   , y_vel    , z_vel,
        #         roll_vel, pitch_vel, yaw_vel,
        #         x_accel , y_accel  , z_accel]
    odom0_differential: false
    odom0_queue_size: 10

    imu0: imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  true, true, false,
                  true, true, true,
                  true, true, true]
        #        [x_pos   , y_pos    , z_pos,
        #         roll    , pitch    , yaw,
        #         x_vel   , y_vel    , z_vel,
        #         roll_vel, pitch_vel, yaw_vel,
        #         x_accel , y_accel  , z_accel]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true